# .circleci/base-config.yml
version: 2.1

jobs:
  setup-sfdx:
    docker:
      - image: salesforce/salesforcedx:latest
    steps:
      - checkout
      - run:
          name: Authenticate with JWT
          command: |
            mkdir -p jwt
            echo "$SFDX_JWT_KEY" | base64 -d > jwt/server.key
            sfdx force:auth:jwt:grant --clientid "$SFDX_CONSUMER_KEY" --jwtkeyfile jwt/server.key --username "$USER_NAME" --setdefaultdevhubusername -a MyHubOrg
      - run:
          name: Change to src/ directory
          command: cd src/
      - run:
          name: Create and set up Scratch Org
          command: |
            sfdx force:org:create -s -f config/project-scratch-def.json -a MyScratchOrg
            sfdx force:config:set defaultusername=MyScratchOrg
