version: 2.1
  orbs:
    apex: circleci/salesforce-apex@x.y
  jobs:
    install_authenticate:
      docker:
        - image: cimg/node:14.5
      steps:
        - checkout
        - apex/setup:
           defaultusername: user@email.com
        - run:
            name: SFDX commands
            command: |
              sf org create scratch --definition-file config/project-scratch-def.json --alias ApexFramework --no-namespace --duration-days 1
  workflows:
    basic-test:
      jobs:
        - install_authenticate