version: 2.1
jobs:
  setup-auth:
    docker:
      - image: cimg/node:20.11
    steps:
      #- checkout 
      - run: 
          name: Install SF CLI
          command: |
            npm install --verbose @salesforce/cli
      - run: 
          name: Authenticate JWT
          command: | 
            echo $SFDX_JWT_KEY | base64 -d - > ~/server.key
            npx sf org login jwt --client-id "$SFDX_CONSUMER_KEY" --jwt-key-file ~/server.key --username "$USER_NAME"
  repo-checkout:
    docker:
      - image: cimg/node:20.11
    steps:
      - run:
          command: | 
            echo ""
workflows:
  setup-auth-workflow:
    jobs:
      - setup-auth