# .circleci/config.yml
version: 2.1

include:
  - base-config.yml
  - feature-config.yml
  - develop-config.yml
  - testing-config.yml
  - release-config.yml

workflows:
  version: 2.1
  feature:
    jobs:
      - setup-sfdx
      - test-changed-classes:
          requires:
            - setup-sfdx
  develop:
    jobs:
      - setup-sfdx
      - test-merged-classes:
          requires:
            - setup-sfdx
  testing:
    jobs:
      - setup-sfdx
      - test-all-classes:
          requires:
            - setup-sfdx
  release:
    jobs:
      - setup-sfdx
      - weekly-test:
          requires:
            - setup-sfdx
