# .circleci/develop-config.yml
jobs:
  check-changes-and-test:
    filters:
      branches:
        only:
          - develop
      schedules:
        - cron: "0 * * * *"
    steps:
      - checkout
      - run:
          name: Identify changed classes modified within the last hour
          command: |
            changed_files=$(git log --since="1 hour ago" --format=format: --name-only $CIRCLE_SHA1)
            test_classes=$(echo "$changed_files" | grep -E 'ClassToBeTested.*\.cls' | sed 's/.cls$/Test/' | sort | uniq)

            # Run tests only for changed test classes
            if [ -n "$test_classes" ]; then
              sfdx force:apex:test:run -n "$test_classes"
            else
              echo "No changed test classes found within the last hour."
            fi

  filters:
    branches:
      only:
        - develop
